<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="30554" started-at="2019-05-09T13:27:09Z" finished-at="2019-05-09T13:27:39Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="30554" started-at="2019-05-09T13:27:09Z" finished-at="2019-05-09T13:27:39Z">
      <class name="TestNGlistnersconcepts.Takescreenshot">
        <test-method status="PASS" signature="setup()[pri:0, instance:TestNGlistnersconcepts.Takescreenshot@6e3c1e69]" name="setup" is-config="true" duration-ms="11236" started-at="2019-05-09T18:57:09Z" finished-at="2019-05-09T18:57:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="TakeScreenshotTest1()[pri:0, instance:TestNGlistnersconcepts.Takescreenshot@6e3c1e69]" name="TakeScreenshotTest1" duration-ms="6" started-at="2019-05-09T18:57:20Z" finished-at="2019-05-09T18:57:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TakeScreenshotTest1 -->
        <test-method status="PASS" signature="quit()[pri:0, instance:TestNGlistnersconcepts.Takescreenshot@6e3c1e69]" name="quit" is-config="true" duration-ms="679" started-at="2019-05-09T18:57:20Z" finished-at="2019-05-09T18:57:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="setup()[pri:0, instance:TestNGlistnersconcepts.Takescreenshot@6e3c1e69]" name="setup" is-config="true" duration-ms="8460" started-at="2019-05-09T18:57:21Z" finished-at="2019-05-09T18:57:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="TakeScreenshotTest2()[pri:0, instance:TestNGlistnersconcepts.Takescreenshot@6e3c1e69]" name="TakeScreenshotTest2" duration-ms="1" started-at="2019-05-09T18:57:30Z" finished-at="2019-05-09T18:57:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TakeScreenshotTest2 -->
        <test-method status="PASS" signature="quit()[pri:0, instance:TestNGlistnersconcepts.Takescreenshot@6e3c1e69]" name="quit" is-config="true" duration-ms="654" started-at="2019-05-09T18:57:30Z" finished-at="2019-05-09T18:57:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="setup()[pri:0, instance:TestNGlistnersconcepts.Takescreenshot@6e3c1e69]" name="setup" is-config="true" duration-ms="7564" started-at="2019-05-09T18:57:31Z" finished-at="2019-05-09T18:57:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="TakeScreenshotTest3()[pri:0, instance:TestNGlistnersconcepts.Takescreenshot@6e3c1e69]" name="TakeScreenshotTest3" duration-ms="20" started-at="2019-05-09T18:57:38Z" finished-at="2019-05-09T18:57:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at TestNGlistnersconcepts.Takescreenshot.TakeScreenshotTest3(Takescreenshot.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TakeScreenshotTest3 -->
        <test-method status="PASS" signature="quit()[pri:0, instance:TestNGlistnersconcepts.Takescreenshot@6e3c1e69]" name="quit" is-config="true" duration-ms="662" started-at="2019-05-09T18:57:39Z" finished-at="2019-05-09T18:57:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- TestNGlistnersconcepts.Takescreenshot -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
